package com.vishal;

import com.vishal.dao.JobDAO;
import com.vishal.model.JobApplication;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class DatabaseConnection {
    public static void main(String[] args) {
        // Date format to parse the date string
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date dateApplied = null;

        try {
            dateApplied = sdf.parse("2025-05-19");
        } catch (ParseException e) {
            e.printStackTrace();
        }

        // Create a job application object with id, company, position, status, and dateApplied
        JobApplication job = new JobApplication(
                0,                          // id, can be 0 or generated by DB
                "Software Engineer",        // position
                "Google",                   // company
                "Applied",                  // status
                dateApplied                 // dateApplied as Date object
        );

        // Create DAO and insert job
        JobDAO dao = new JobDAO();
        dao.insertJob(job);
    }
}
